CREATE TABLE resource_service."workplace" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "address" varchar NOT NULL,
  "zone" varchar NOT NULL,
  "floor" varchar,
  "number" int NOT NULL,
  "type" varchar NOT NULL,
  "capacity" int NOT NULL,
  "description" text,
  "is_available" boolean DEFAULT true
);

CREATE TABLE resource_service."items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" varchar NOT NULL,
  "name" varchar NOT NULL,
  "condition_id" int NOT NULL,
  "workplace_id" int,
  FOREIGN KEY ("workplace_id") REFERENCES resource_service."workplace" ("id") ON DELETE SET NULL,
  FOREIGN KEY ("condition_id") REFERENCES resource_service."item_conditions" ("id")
);

CREATE TABLE resource_service."item_conditions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "value" varchar NOT NULL,
  "description" text
);

CREATE TABLE resource_service."resource_tags" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL UNIQUE
);
CREATE TABLE resource_service."workplace_tags" (
  "workplace_id" int NOT NULL,
  "tag_id" int NOT NULL,
  PRIMARY KEY ("workplace_id", "tag_id"),
  FOREIGN KEY ("workplace_id") REFERENCES resource_service."workplace" ("id") ON DELETE CASCADE,
  FOREIGN KEY ("tag_id") REFERENCES resource_service."resource_tags" ("id") ON DELETE CASCADE
);

Create table resource_service."parking_spaces"(
  "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "address" varchar NOT NULL,
  "zone" varchar NOT NULL,
  "number" int NOT NULL,
  "floor" varchar,
  "type" VARCHAR not null,
  "is_available" boolean DEFAULT true
);

CREATE INDEX idx_workplace_zone ON resource_service.workplace(zone);
CREATE INDEX idx_workplace_floor ON resource_service.workplace(floor);
CREATE INDEX idx_workplace_type ON resource_service.workplace(type);
CREATE INDEX idx_workplace_is_available ON resource_service.workplace(is_available);

CREATE INDEX idx_items_workplace_id ON resource_service.items(workplace_id);
CREATE INDEX idx_items_type ON resource_service.items(type);